### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by guidol** [browneyedsoul/RemNote-RemTree#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hello Minki,

Looks, web-version works!!. Sorry for the delayed answer.
Are you Korean?

![image](https://user-images.githubusercontent.com/19164042/205928408-58e19721-2863-4b63-aec1-6cfb9e90bf21.png)

**Comment by browneyedsoul** [comment]
네 안녕하세요 코리언ㅋㅋ 잘 작동하는것 같네요 그런데 데스크탑앱에서 안되었던 건가요? 태그부분이 예상치 못한거라 스스로 수정하신건지 잘 가늠이 안되네요 :)
혹시 채팅이 가능하시다면 https://discord.gg/ZZPQQCBs 여기로 오시면 됩니다 ^^

**Comment by guidol** [comment]
아 제가 디스코드가 익숙치 않아서... 일단 들어갔는데 민기님을 찾을수가 없네요... 저는 대화명이 귀돌입니다.
